version: "2.3"
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ={{ TZ }}
    ports:
      - 33377:80
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.librespeed.rule=Host(`speed.jakehoward.tech`)
      - traefik.http.routers.librespeed.middlewares=librespeed-auth@docker
      - traefik.http.middlewares.librespeed-auth.basicauth.users={{ librespeed_basicauth }}
