- name: Include vault
  include_vars: vault.yml

- name: Create install directory
  file:
    path: /opt/gitea
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/gitea/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart gitea
  become: true

- name: Install config file
  template:
    src: files/app.ini
    dest: "{{ app_data_dir }}/gitea/config/app.ini"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart gitea
  become: true
