- name: Include wallabag variables
  include_vars: wallabag.yml

- name: Create wallabag directory
  file:
    path: /opt/wallabag
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install wallabag compose file
  template:
    src: files/wallabag/docker-compose.yml
    dest: /opt/wallabag/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  register: compose_file
  become: true

- name: restart wallabag
  shell:
    chdir: /opt/wallabag
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed
