- name: restart coredns
  service:
    name: coredns
    state: restarted
    enabled: true
  become: true

- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
    enabled: true
  become: true
