- name: Include vault
  include_vars: vault.yml

- name: Create install directory
  file:
    path: /opt/comentario
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/comentario/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart comentario

- name: Install secrets
  copy:
    content: "{{ comentario_secrets | to_nice_yaml }}"
    dest: /opt/comentario/secrets.yml
    mode: "600"
    owner: "{{ docker_user.name }}"
  notify: restart comentario
