gitlab_config_template: files/gitlab.rb
gitlab_create_self_signed_cert: false
gitlab_smtp_password: "{{ vault_gitlab_smtp_password }}"
gitlab_smtp_user: "{{ vault_gitlab_smtp_user }}"
gitlab_from_email: "{{ vault_gitlab_from_email }}"
