- name: Include vault
  include_vars: vault.yml

- name: Install Headscale
  package:
    name: headscale
  become: true

- name: Install headscale config file
  template:
    src: files/headscale.yml
    dest: /etc/headscale/config.yaml
    owner: headscale
    mode: "0600"
  notify: restart headscale
  become: true

- name: Install ACLs
  template:
    src: files/acls.json
    dest: /etc/headscale/acls.json
    owner: headscale
    mode: "0600"
  notify: restart headscale
  become: true

- name: Install nginx config
  template:
    src: files/nginx.conf
    dest: /etc/nginx/http.d/headscale.conf
    mode: "0644"
  become: true
  notify: reload nginx
