services:
  coredns:
    image: coredns/coredns:latest
    restart: unless-stopped
    volumes:
      - ./Corefile:/Corefile:ro
    ports:
      - "{{ private_ip }}:53053:53/udp"
    networks:
      - default
      - coredns

networks:
  coredns:
    external: true
