private_ip: "{{ pve_hosts.pve.ip }}"

zpools_to_scrub:
  - tank
  - rpool

# 5GB, or so
zfs_arc_size: 5000000000

sanoid_datasets:
  tank:
    use_template: production
    recursive: true
    process_children_only: true

  rpool:
    use_template: production
    recursive: true

sanoid_templates:
  production:
    frequently: 2
    hourly: 48
    daily: 28
    monthly: 3
    yearly: 0
    autosnap: true
    autoprune: true

  replaceable:
    frequently: 0
    hourly: 24
    daily: 7
    monthly: 0
    yearly: 0
    autosnap: true
    autoprune: true


# Snapraid
snapraid_install: false
snapraid_runner: false

snapraid_data_disks:
  - path: /mnt/bulk
    content: true
snapraid_parity_disks:
  - path: /mnt/parity
    content: true

snapraid_content_files:
  - /var/snapraid.content
  - /mnt/tank/files/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - /tmp/

snapraid_scrub_schedule:
  hour: 2
  weekday: 4

snapraid_scrub_healthcheck_io_uuid: "{{ vault_snapraid_scrub_healthcheck_io_uuid }}"
snapraid_sync_healthcheck_io_uuid: "{{ vault_snapraid_sync_healthcheck_io_uuid }}"
