- name: restart wireguard
  service:
    name: wg-quick@wg0
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload nftables
  command:
    argv:
      - nft
      - -f
      - /etc/nftables.conf
