- name: restart wireguard
  service:
    name: wg-quick@wg0
    state: restarted
  become: true

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true

- name: reload nftables
  command:
    argv:
      - nft
      - -f
      - /etc/nftables.conf
  become: true
