terraform:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  before_script:
    - apk add --no-cache bash
    - ./scripts/terraform/terraform.sh init -backend=false
  script:
    - ./scripts/terraform/lint.sh

ansible:
  image: python:3.9-slim
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  before_script:
    - apt-get update && apt-get install -y bash git
    - ./scripts/ansible/setup.sh
  script:
    - ./scripts/ansible/lint.sh
