services:
  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:12
    user: "{{ docker_user.id }}"
    volumes:
      - /mnt/data:/data
      - ./config.yml:/data/config.yml
    environment:
      - TZ={{ timezone }}
    restart: unless-stopped
    command: forgejo-runner --config config.yml daemon
    depends_on:
      - dind
    ports:
      - "{{ ansible_default_ipv4.address }}:4000:4000"

  dind:
    image: docker:dind
    environment:
      - TZ={{ timezone }}
      - DOCKER_HOST=tcp://0.0.0.0:2375
    volumes:
      - /mnt/ci-runner-docker:/var/lib/docker
    privileged: true
    restart: unless-stopped
    command: dockerd -H tcp://0.0.0.0:2375 --tls=false
