version: "2.3"
services:
  duplicati:
    image: linuxserver/duplicati:version-v2.0.5.1-2.0.5.1_beta_2020-01-18
    hostname: "{{ ansible_fqdn }}"
    environment:
      - PUID=0
      - PGID=0
      - TZ={{ TZ }}
    volumes:
      - ./config:/config
      - ./restore:/restore
      - /:/source:ro
    restart: unless-stopped
    ports:
      - "{{ protected_ip }}:8200:8200"
