# Just the keys I need. See https://github.com/matrix-org/synapse/blob/develop/docs/sample_config.yaml

## Server ##

server_name: theorangeone.net

pid_file: /data/homeserver.pid

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true

    resources:
      - names: [client, federation]
        compress: false

## TLS ##

acme:
  # ACME support is disabled by default. Set this to `true` and uncomment
  # tls_certificate_path and tls_private_key_path above to enable it.
  #
  enabled: false

## Database ##

database:
  # The database engine name
  name: psycopg2
  # Arguments to pass to the engine
  args:
    user: synapse
    password: synapse
    database: synapse
    host: db

## Logging ##

log_config: /data/theorangeone.net.log.config

## Media Store ##

media_store_path: /data/media_store

uploads_path: /data/uploads

## Registration ##

registration_shared_secret: "{{ synapse.registration_shared_secret }}"

## Metrics ###

report_stats: true

## API Configuration ##

macaroon_secret_key: "{{ synapse.macaroon_secret_key }}"

form_secret: "{{ synapse.form_secret }}"

## Signing Keys ##

signing_key_path: /data/theorangeone.net.signing.key

key_refresh_interval: 2w

trusted_key_servers:
  - server_name: matrix.org

suppress_key_server_warning: true
