private_ip: "{{ pve_hosts.pve_docker.ip }}"
protected_ip: "{{ pve_hosts.pve_docker.internal_ip }}"

traefik_provider_jellyfin: true
traefik_provider_homeassistant: true
traefik_provider_grafana: true
