private_ip: "{{ pve_hosts.pve.ip }}"

zpools_to_scrub:
  - tank
  - rpool

# 10GB, or so
zfs_arc_size: 10000000000

sanoid_datasets:
  tank:
    use_template: production
    recursive: true
    process_children_only: true

  rpool:
    use_template: production
    recursive: true

# Snapraid
snapraid_install: false
snapraid_runner: false

snapraid_data_disks:
  - path: /mnt/bulk
    content: true
snapraid_parity_disks:
  - path: /mnt/parity
    content: true

snapraid_content_files:
  - /mnt/tank/files/snapraid.content
  - /var/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - /tmp/

snapraid_scrub_schedule:
  hour: 5
  weekday: 4
