expose_ssh: true

private_ip: "{{ pve_hosts.pve.ip }}"
protected_ip: "{{ pve_hosts.pve.internal_ip }}"

zpools_to_scrub:
  - tank
  - rpool

# 5GB, or so
zfs_arc_size: 5000000000

sanoid_datasets:
  tank:
    use_template: production
    recursive: true
    process_children_only: true

  rpool:
    use_template: production
    recursive: true
