private_ip: "{{ pve_hosts.pve.ip }}"

zpools_to_scrub:
  - tank
  - rpool

# 10GB, or so
zfs_arc_size: 10000000000

sanoid_datasets:
  tank:
    use_template: production
    recursive: true
    process_children_only: true

  rpool:
    use_template: production
    recursive: true
