version: "2.3"

services:
  commento:
    image: ghcr.io/souramoo/commentoplusplus:latest
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.commento.rule=Host(`commento.theorangeone.net`)
    environment:
      - COMMENTO_POSTGRES=postgres://commento:commento@db:5432/commento?sslmode=disable
      - COMMENTO_ORIGIN=https://commento.theorangeone.net
      - COMMENTO_GZIP_STATIC=true
      - COMMENTO_FORBID_NEW_OWNERS=true
      - COMMENTO_GITHUB_KEY={{ commento_github_client_id }}
      - COMMENTO_GITHUB_SECRET={{ commento_github_client_secret }}
      - COMMENTO_SMTP_HOST=smtp.fastmail.com
      - COMMENTO_SMTP_PORT=465
      - COMMENTO_SMTP_USERNAME={{ commento_smtp_username }}
      - COMMENTO_SMTP_PASSWORD={{ commento_smtp_password }}
      - COMMENTO_SMTP_FROM_ADDRESS={{ commento_from_email }}
      - COMMENTO_GITLAB_KEY={{ commento_gitlab_application_id }}
      - COMMENTO_GITLAB_SECRET={{ commento_gitlab_application_secret }}

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=commento
      - POSTGRES_USER=commento

networks:
  traefik:
    external: true
