services:
  slides:
    image: ghcr.io/realorangeone/slides:latest
    restart: unless-stopped
    environment:
      - TZ={{ timezone }}
      - PUID={{ docker_user.id }}
    volumes:
      - ./htpasswd:/etc/nginx/.htpasswd:ro
      - ./slides:/srv
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.slides.rule=Host(`slides.jakehoward.tech`)

networks:
  traefik:
    external: true
