- name: Create install directory
  file:
    path: /opt/pages
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Create sites directory
  file:
    path: /opt/pages/sites
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/pages/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart pages
  become: true

- name: Create superuser
  htpasswd:
    path: /opt/pages/htpasswd.txt
    name: jake
    password: "{{ superuser_password }}"
    mode: 0640
    owner: "{{ docker_user.name }}"
  become: true

- name: Create GitHub user
  htpasswd:
    path: /opt/pages/htpasswd.txt
    name: github
    password: "{{ github_user_password }}"
    mode: 0640
  become: true
