version: "2.3"

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - TZ={{ TZ }}
      - GF_DATABASE_URL=postgres://grafana:grafana@db/grafana
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    volumes:
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - db
      - renderer

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=grafana
      - POSTGRES_USER=grafana

  renderer:
    image: grafana/grafana-image-renderer:latest
    restart: unless-stopped
    environment:
      - BROWSER_TZ={{ TZ }}
