scrape_configs:
  - job_name: telegraf
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.+
        action: drop

    static_configs:
      - targets:
          - telegraf:9273
  - job_name: traefik
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.+
        action: drop

    static_configs:
      - targets:
          - 10.23.2.3:8080  # grimes
          - 192.168.2.47:8080  # pve-docker
