scrape_configs:
  - job_name: telegraf
    static_configs:
      - targets:
          - telegraf:9273
  - job_name: traefik
    static_configs:
      - targets:
          - 10.23.2.3:8080  # grimes
          - 192.168.2.47:8080  # pve-docker
