version: "2.3"

services:
  deluge:
    image: linuxserver/deluge:latest
    network_mode: host
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ={{ TZ }}
    volumes:
      - ./deluge:/config
      - /mnt/downloads:/downloads
    restart: unless-stopped

  egress:
    image: theorangeone/static-server:latest
    restart: unless-stopped
    environment:
      - INDEX=on
    volumes:
      - /mnt/downloads:/srv:ro
    ports:
      - 80:80
