on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - uses: extractions/setup-just@v1
      - name: Init
        run: just terraform init -backend=false
      - name: Lint
        run: just terraform-lint

  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: extractions/setup-just@v1

      # HACK: https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
      - name: Fix permissions
        run: chmod 0755 ansible/

      - name: Set up
        run: just ansible-setup
      - name: Lint
        run: just ansible-lint
