private_ip: "{{ ansible_tailscale0.ipv4.address }}"
nginx_https_redirect: true

certbot_certs:
  - domains:
      - headscale.jakehoward.tech
  - domains:
      - whoami-cdn.theorangeone.net

cdn_domains:
  - whoami-cdn.theorangeone.net

restic_backup_locations:
  - /var/lib/headscale/
