nebula_is_lighthouse: true
nebula_listen_port: "{{ nebula_lighthouse_port }}"
ssh_extra_allowed_users: f2b@{{ nebula.cidr }} f2b@{{ pve_hosts.internal_cidr }} f2b@{{ tailscale_cidr }}

nginx_https_redirect: true

certbot_certs:
  - domains:
      - headscale.jakehoward.tech

restic_backup_locations:
  - /var/lib/headscale/
