global:
  resolve_timeout: 3m
  smtp_smarthost: smtp.eu.mailgun.org:465
  smtp_from: "{{ vault_alertmanager_from_address }}"
  smtp_auth_username: "{{ vault_alertmanager_from_address }}"
  smtp_auth_password: "{{ vault_alertmanager_smtp_password }}"

route:
  receiver: default

receivers:
  - name: default
    email_configs:
      - to: "{{ vault_alertmanager_to_address }}"
        send_resolved: true
