modules:
  http:
    prober: http
    timeout: 10s
    http:
      preferred_ip_protocol: ip4  # Docker network is v4 only

  https_redir:
    prober: http
    timeout: 10s
    http:
      method: GET
      valid_status_codes: [301, 302, 307, 308]
      no_follow_redirects: true
      fail_if_ssl: true
      fail_if_header_not_matches:
        - header: Location
          regexp: ^https
      preferred_ip_protocol: ip4  # Docker network is v4 only

  icmp:
    prober: icmp
