version: "2.3"

x-blackbox: &blackbox
  image: prom/blackbox-exporter:latest
  restart: unless-stopped
  user: "{{ docker_user.id }}"
  volumes:
    - ./blackbox.yml:/etc/blackbox_exporter/config.yml:ro

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    user: "{{ docker_user.id }}"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /mnt/tank/dbs/prometheus/forrest/:/prometheus/
    networks:
      - default
      - grafana
    ports:
      - "{{ pve_hosts.forrest.ip }}:9090:9090"

  blackbox:
    <<: *blackbox

  blackbox-external:
    <<: *blackbox
    # Don't use my internal DNS servers
    dns:
      - 9.9.9.9
      - 149.112.112.112

  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    user: "{{ docker_user.id }}"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

  proxmox_exporter:
    image: prompve/prometheus-pve-exporter:latest
    restart: unless-stopped
    user: "{{ docker_user.id }}"
    environment:
      - PVE_USER=prometheus@pve
      - PVE_TOKEN_NAME=prometheus
      - PVE_TOKEN_VALUE={{ prometheus_api_token }}
      - PVE_VERIFY_SSL=false

  speedtest_exporter:
    image: jraviles/prometheus_speedtest:latest
    restart: unless-stopped
    user: "{{ docker_user.id }}"

networks:
  grafana:
    external: true
