version: "2.3"

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/tank/dbs/prometheus/forrest/:/prometheus/
    networks:
      - default
      - prometheus
      - grafana
    ports:
      - "{{ pve_hosts.forrest.ip }}:9090:9090"

  blackbox:
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml

networks:
  prometheus:
    external: true
  grafana:
    external: true
