scrape_configs:
  - job_name: telegraf
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.+
        action: drop

    static_configs:
      - targets:
          - "{{ pve_hosts.pve.ip }}:9273"
  - job_name: traefik
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.+
        action: drop

    static_configs:
      - targets:
          - "{{ nebula.clients.walker.ip }}:8080"
          - "{{ pve_hosts.docker.ip }}:8080"
