version: "2.3"
services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ={{ TZ }}
    restart: unless-stopped
    volumes:
      - /mnt/tank/app-data/calibre:/config
      - /mnt/tank/files/ebooks:/books:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre.rule=Host(`calibre.jakehoward.tech`)
      - traefik.http.routers.calibre.tls.certresolver=le
