- name: Add Jellyfin apt key
  ansible.builtin.apt_key:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    state: present

- name: Add Jellyfin repository
  apt_repository:
    repo: deb [arch=amd64] https://repo.jellyfin.org/debian {{ ansible_distribution_release }} main
    filename: jellyfin
    state: present

- name: Install jellyfin
  package:
    name: jellyfin

- name: Set media dir permissions
  cron:
    name: Set media permissions
    special_time: daily
    job: chown -R jellyfin:jellyfin /mnt/media
