- name: Add Jellyfin apt key
  ansible.builtin.apt_key:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    state: present
  become: true

- name: Add Jellyfin repository
  apt_repository:
    repo: deb [arch=amd64] https://repo.jellyfin.org/debian buster main
    filename: jellyfin
    state: present
  become: true

- name: Install jellyfin
  package:
    name: jellyfin
  become: true
