- name: Create jail
  template:
    src: files/fail2ban/traefik-jail.conf
    dest: /etc/fail2ban/jail.d/traefik.conf
    mode: "644"
  become: true
  notify: restart fail2ban

- name: Create filter
  template:
    src: files/fail2ban/traefik-filter.conf
    dest: /etc/fail2ban/filter.d/traefik.conf
    mode: "644"
  become: true
  notify: restart fail2ban

- name: Create action
  template:
    src: files/fail2ban/remote-action.conf
    dest: /etc/fail2ban/action.d/gateway.conf
    mode: "644"
  become: true
  notify: restart fail2ban

- name: Create SSH key
  copy:
    src: files/fail2ban/f2b_key.key
    dest: /etc/fail2ban/f2b_key.key
    owner: root
    group: root
    mode: "0600"
  become: true
