version: "2.3"

services:
  webdav:
    image: ghcr.io/realorangeone/webdav:latest
    restart: unless-stopped
    volumes:
      - ./sites:/srv
      - ./htpasswd.txt:/etc/nginx/.htpasswd:ro
    environment:
      - PUID={{ docker_user.id }}
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.pages.rule=Host(`pages.theorangeone.net`)

  traefik-pages:
    image: ghcr.io/realorangeone/traefik-pages:latest
    volumes:
      - ./sites:/sites:ro
    restart: unless-stopped
    user: "{{ docker_user.id }}"
    environment:
      - SITES_ROOT=/sites
      - TRAEFIK_SERVICE=traefik-pages-pages@docker
      - AUTH_PASSWORD={{ traefik_pages_password }}
      - TRAEFIK_CERT_RESOLVER=le
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true

networks:
  traefik:
    external: true
