alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alert-rules.d/*.yml

scrape_configs:
  - job_name: pve
    static_configs:
      - targets:
          - "{{ pve_hosts.pve.ip }}"
    metrics_path: /pve
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: proxmox_exporter:9221

  - job_name: traefik
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.+
        action: drop
    static_configs:
      - targets:
          - "{{ pve_hosts.docker.ip }}:8080"

  - job_name: homeassistant
    metrics_path: /api/prometheus
    authorization:
      credentials: "{{ vault_homeassistant_token }}"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: python_.+
        action: drop
    static_configs:
      - targets: ["{{ pve_hosts.homeassistant.ip }}:8123"]

  - job_name: blackbox_icmp
    scrape_interval: 10m
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - "{{ pve_hosts.pve.ip }}"
          - "{{ pve_hosts.homeassistant.ip }}"
          - 9.9.9.9
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: blackbox_https_redir
    scrape_interval: 10m
    metrics_path: /probe
    params:
      module: [https_redir]
    static_configs:
      - targets:
          - http://{{ vps_hosts.casey_ip }}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: blackbox_healthcheck
    scrape_interval: 10m
    metrics_path: /probe
    params:
      module: [http]
    static_configs:
      - targets:
          - https://hc-ping.com/{{ vault_prometheus_healthcheck_uuid }}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: healthchecks
    scheme: https
    metrics_path: /projects/{{ vault_healthchecks_project_uuid }}/metrics/{{ vault_healthcheck_api_token }}
    static_configs:
      - targets: [healthchecks.io]

  - job_name: node
    metrics_path: /metrics
    static_configs:
      - targets:
          - "{{ pve_hosts.pve.ip }}:9100"
          - 192.168.1.53:9100  # adguardhome
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.+
        action: drop

  - job_name: speedtest
    scrape_interval: 1h
    scrape_timeout: 2m
    metrics_path: /probe
    static_configs:
      - targets:
          - speedtest_exporter:9516

  - job_name: headscale
    metrics_path: /metrics
    static_configs:
      - targets:
          - "{{ tailscale_nodes.casey.ip }}:9090"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.+
        action: drop

  - job_name: uptime_kuma
    basic_auth:
      username: ""
      password: "{{ vault_uptime_kuma_token }}"
    metrics_path: /metrics
    static_configs:
      - targets:
          - uptime.jakehoward.tech
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: nodejs_.+
        action: drop
      - source_labels: [__name__]
        regex: process_.+
        action: drop
