- name: Create network
  docker_network:
    name: coredns
    internal: true
  become: true

- name: Create install directory
  file:
    path: /opt/coredns
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/coredns/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart coredns
  become: true
