- name: Create network
  docker_network:
    name: coredns

- name: Create install directory
  file:
    path: /opt/coredns
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/coredns/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart coredns

- name: Install Corefile
  template:
    src: files/Corefile
    dest: /opt/coredns/Corefile
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart coredns
