website_secret_key: "{{ vault_website_secret_key }}"
website_sentry_dsn: "{{ vault_website_sentry_dsn }}"
unsplash_client_id: "{{ vault_unsplash_client_id }}"
spotify_client_id: "{{ vault_spotify_client_id }}"
spotify_client_secret: "{{ vault_spotify_client_secret }}"
spotify_sentry_dsn: "{{ vault_spotify_sentry_dsn }}"
