version: "2.3"

services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    environment:
      - TZ={{ timezone }}
    volumes:
      - "{{ app_data_dir }}/privatebin/:/srv/data"
      - "{{ app_data_dir }}/privatebin/conf.php:/srv/cfg/conf.php:ro"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.privatebin.rule=Host(`bin.theorangeone.net`)
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
