- name: Install Pacman utils
  package:
    name: pacman-contrib

- name: Create hooks directory
  file:
    path: /etc/pacman.d/hooks/
    state: directory
    mode: "0755"

- name: Install pacman hook
  template:
    src: files/paccache.hook
    dest: /etc/pacman.d/hooks/clean_package_cache.hook
    mode: "0644"
