- name: Create network
  docker_network:
    name: grafana

- name: Create grafana install directory
  file:
    path: /opt/grafana
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install grafana compose file
  template:
    src: files/grafana/docker-compose.yml
    dest: /opt/grafana/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart grafana
  become: true
