- name: Create influxdb install directory
  file:
    path: /opt/influxdb
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install influxdb compose file
  template:
    src: files/influxdb/docker-compose.yml
    dest: /opt/influxdb/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart influxdb
  become: true
