- name: Include vault
  include_vars: vault.yml

- name: Grafana
  include_tasks: grafana.yml

- name: Prometheus
  include_tasks: prometheus.yml

- name: Get routes
  command:
    argv:
      - ip
      - -6
      - route
      - show
      - "{{ vps_hosts.private_ipv6_range }}"
  register: routes
  changed_when: false
  become: true

- name: Add route to private services via ingress
  command:
    argv:
      - ip
      - -6
      - route
      - add
      - "{{ vps_hosts.private_ipv6_range }}"
      - via
      - "{{ pve_hosts.ingress.link_local }}"
      - dev
      - eth0
  become: true
  when: vps_hosts.private_ipv6_marker not in routes.stdout
