- name: Create network
  docker_network:
    name: prometheus

- name: Create prometheus install directory
  file:
    path: /opt/prometheus
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install prometheus compose file
  template:
    src: files/docker-compose-prometheus.yml
    dest: /opt/prometheus/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart prometheus
  become: true
