- name: Include vault
  include_vars: vault.yml

- name: Create install directory
  file:
    path: /opt/website
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/website/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart website

- name: Install nginx config
  template:
    src: files/nginx-docker.conf
    dest: /etc/nginx/http.d/website.conf
    mode: "0644"
  notify: reload nginx
  vars:
    server_name: theorangeone.net jakehoward.tech
    upstream: website-website-1.docker:8000
    ssl_cert_path: /etc/letsencrypt/live/theorangeone.net
    location_extra: |
      more_set_headers "Server: $upstream_http_server";
