- name: Include vault
  include_vars: vault.yml

- name: Install wireguard tools
  package:
    name: "{{ item }}"
  loop:
    - wireguard-tools
    - qrencode

- name: Wireguard server config
  template:
    src: files/server.conf
    dest: /etc/wireguard/glinet.conf
    mode: "0600"
    backup: true
  notify: restart wireguard

- name: Wireguard client config
  template:
    src: files/client.conf
    dest: "{{ me.home }}/glinet-vpn.conf"
    mode: "0600"
    owner: "{{ me.user }}"
  notify: restart wireguard

- name: Enable wireguard
  service:
    name: wg-quick@glinet
    enabled: true
