version: "2.3"

services:
  influxdb:
    image: influxdb:1.8-alpine
    restart: unless-stopped
    volumes:
      - /mnt/tank/dbs/influx/forrest:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    networks:
      - default
      - grafana

  chronograf:
    image: chronograf:1.8-alpine
    restart: unless-stopped
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=influxadmin
      - INFLUXDB_PASSWORD={{ influxdb_admin_password }}
    volumes:
      - ./chronograf:/var/lib/chronograf
    ports:
      - "{{ private_ip }}:8888:8888"

networks:
  grafana:
    external: true
