- name: Create calibre directory
  file:
    path: /opt/calibre
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install calibre compose file
  template:
    src: files/calibre/docker-compose.yml
    dest: /opt/calibre/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  register: compose_file
  become: true

- name: restart calibre
  shell:
    chdir: /opt/calibre
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed
