remark_github_client_id: "{{ vault_remark_github_client_id }}"
remark_github_client_secret: "{{ vault_remark_github_client_secret }}"
remark_smtp_username: "{{ vault_remark_smtp_username }}"
remark_smtp_password: "{{ vault_remark_smtp_password }}"
remark_from_email: "{{ vault_remark_from_email }}"
remark_secret: "{{ vault_remark_secret }}"
remark_admin_password: "{{ vault_remark_admin_password }}"
remark_admin_email: "{{ vault_remark_admin_email }}"
