- name: Create install directory
  file:
    path: /opt/privatebin
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/privatebin/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart privatebin

- name: Install config file
  template:
    src: files/config.ini
    dest: "{{ app_data_dir }}/privatebin/conf.php"  # Yes, really
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart privatebin
