services:
  website:
    image: git.theorangeone.net/private-packages/theorangeone.net:latest
    restart: unless-stopped
    environment:
      - TZ={{ timezone }}
      - DEBUG=false
      - SECRET_KEY={{ vault_website_secret_key }}
      - UNSPLASH_CLIENT_ID={{ vault_unsplash_client_id }}
      - SENTRY_DSN={{ vault_website_sentry_dsn }}
      - FLICKR_API_KEY={{ vault_flickr_api_key }}
      - PLAUSIBLE_API_KEY={{ vault_plausible_api_key }}
      - GRANIAN_WORKERS={{ ansible_processor_nproc * 2 + 1 }}
    volumes:
      - ./cache:/app/.cache/persistent
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.rule=Host(`theorangeone.net`) || Host(`jakehoward.tech`)
      - traefik.http.middlewares.website-redirect.redirectregex.regex=^https://jakehoward.tech/(.*)
      - traefik.http.middlewares.website-redirect.redirectregex.replacement=https://theorangeone.net/$${1}
      - traefik.http.routers.website.middlewares=website-redirect@docker

networks:
  traefik:
    external: true
