version: "2.3"

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - TZ={{ TZ }}
      - GF_DATABASE_URL=postgres://grafana:grafana@db/grafana
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_SERVER_ROOT_URL=https://grafana.jakehoward.tech
      - GF_SERVER_ENABLE_GZIP=true

      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.fastmail.com:465
      - GF_SMTP_USER={{ grafana_smtp_user }}
      - GF_SMTP_PASSWORD={{ grafana_smtp_password }}
      - GF_SMTP_FROM_ADDRESS={{ grafana_from_email }}
      - GF_SMTP_FROM_NAME=grafana
    volumes:
      - "{{ app_data_dir }}/grafana:/var/lib/grafana"
    networks:
      - default
      - grafana
    restart: unless-stopped
    ports:
      - "{{ pve_hosts.forrest.ip }}:3000:3000"
    depends_on:
      - db
      - renderer

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - /mnt/tank/dbs/postgres/grafana/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=grafana
      - POSTGRES_USER=grafana

  renderer:
    image: grafana/grafana-image-renderer:latest
    restart: unless-stopped
    environment:
      - BROWSER_TZ={{ TZ }}


networks:
  grafana:
    external: true
