- name: Include variables
  include_vars: upload.yml

- name: Create install directory
  file:
    path: /opt/upload
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/upload/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart upload
  become: true

- name: Create superuser
  htpasswd:
    path: /opt/upload/htpasswd.txt
    name: jake
    password: "{{ superuser_upload_password }}"
    mode: "640"
    owner: "{{ docker_user.name }}"
  become: true

- name: Create nextcloud user
  htpasswd:
    path: /opt/upload/htpasswd.txt
    name: nextcloud
    password: "{{ nextcloud_upload_password }}"
    mode: "640"
  become: true
