- name: restart grafana
  shell:
    chdir: /opt/grafana
    cmd: "{{ docker_update_command }}"

- name: restart influxdb
  shell:
    chdir: /opt/influxdb
    cmd: "{{ docker_update_command }}"

- name: restart prometheus
  shell:
    chdir: /opt/prometheus
    cmd: "{{ docker_update_command }}"
