collections:
  - ansible.posix
  - community.general
  - community.docker
  - amazon.aws  # Dependency of rossmcdonald.telegraf

roles:
  - src: geerlingguy.docker
  - src: geerlingguy.ntp
  - src: realorangeone.reflector
  - src: https://github.com/IronicBadger/ansible-role-proxmox-nag-removal
    name: IronicBadger.proxmox-nag-removal
  - src: chmduquesne.iptables_persistent
  - src: rossmcdonald.telegraf
  - src: geerlingguy.gitlab
  - src: dokku_bot.ansible_dokku
  - src: https://github.com/IronicBadger/ansible-role-snapraid
    name: IronicBadger.snapraid
