collections:
  - ansible.posix
  - community.general
  - community.docker
  - name: https://github.com/prometheus-community/ansible
    type: git

roles:
  - src: geerlingguy.docker
    version: 6.1.0
  - src: geerlingguy.ntp
    version: 2.3.3
  - src: realorangeone.reflector
  - src: ironicbadger.proxmox_nag_removal
    version: 1.0.2
  - src: chmduquesne.iptables_persistent
  - src: dokku_bot.ansible_dokku
    version: v2022.10.17
  - src: ironicbadger.snapraid
    version: 1.0.0
