collections:
  - ansible.posix
  - community.general
  - community.docker
  - name: https://github.com/prometheus-community/ansible
    type: git

roles:
  - src: geerlingguy.docker
    version: 4.2.3
  - src: geerlingguy.ntp
    version: 2.3.1
  - src: realorangeone.reflector
  - src: ironicbadger.proxmox_nag_removal
    version: 1.0.1
  - src: chmduquesne.iptables_persistent
  - src: dokku_bot.ansible_dokku
    version: v2021.11.28
  - src: ironicbadger.snapraid
    version: 1.0.0
