collections:
  - ansible.posix
  - community.general
  - community.docker
  - amazon.aws  # Dependency of rossmcdonald.telegraf

roles:
  - src: geerlingguy.docker
  - src: https://github.com/dlerch-tpgroup/ansible-role-ntp  # https://github.com/geerlingguy/ansible-role-ntp/pull/84
    name: geerlingguy.ntp
  - src: realorangeone.reflector
  - src: https://github.com/IronicBadger/ansible-role-proxmox-nag-removal
    name: proxmox-nag-removal
  - src: chmduquesne.iptables_persistent
  - src: rossmcdonald.telegraf
  - src: geerlingguy.gitlab
