collections:
  - ansible.posix
  - community.general
  - community.docker
  - kewlfft.aur
  - name: https://github.com/prometheus-community/ansible
    type: git

roles:
  - src: geerlingguy.docker
    version: 7.4.3
  - src: geerlingguy.ntp
    version: 2.7.0
  - src: realorangeone.reflector
  - src: ironicbadger.proxmox_nag_removal
    version: 1.0.2
  - src: ironicbadger.snapraid
    version: 1.0.0
  - src: geerlingguy.certbot
    version: 5.4.1
  - src: artis3n.tailscale
    version: v4.5.0
