collections:
  - ansible.posix
  - community.general
  - community.docker
  - amazon.aws  # Dependency of rossmcdonald.telegraf

roles:
  - src: geerlingguy.docker
    version: 4.2.3
  - src: geerlingguy.ntp
    version: 2.3.1
  - src: realorangeone.reflector
  - src: ironicbadger.proxmox_nag_removal
    version: 1.0.1
  - src: chmduquesne.iptables_persistent
  - src: rossmcdonald.telegraf
    version: v1.2.0
  - src: geerlingguy.gitlab
    version: 3.2.0
  - src: dokku_bot.ansible_dokku
    version: v2021.11.28
  - src: ironicbadger.snapraid
    version: 1.0.0
