- name: Create quassel directory
  file:
    path: /opt/quassel
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install quassel compose file
  template:
    src: files/quassel/docker-compose.yml
    dest: /opt/quassel/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  register: compose_file
  become: true

- name: restart quassel
  shell:
    chdir: /opt/quassel
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed
