http:
  routers:
    router-grafana:
      rule: Host(`grafana.jakehoward.tech`)
      service: service-grafana
  services:
    service-grafana:
      loadBalancer:
        servers:
          - url: http://{{ pve_hosts.forrest.ip }}:3000
