http:
  middlewares:
    tls-redirect:
      redirectScheme:
        scheme: https
    compress:
      compress: {}

    # https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network
    floc-block:
      headers:
        customResponseHeaders:
          Permissions-Policy: interest-cohort=()
