http:
  routers:
    router-homeassistant:
      rule: Host(`homeassistant.jakehoward.tech`)
      service: service-homeassistant
      tls:
        certResolver: le
  services:
    service-homeassistant:
      loadBalancer:
        servers:
          - url: http://{{ pve_hosts.homeassistant.ip }}:8123
