http:
  routers:
    router-gitlab:
      rule: Host(`git.theorangeone.net`)
      service: service-gitlab
    router-gitlab-registry:
      rule: Host(`registry.git.theorangeone.net`)
      service: service-gitlab
    router-gitlab-pages:
      rule: HostRegexp(`gitlab-pages.theorangeone.net`, `{subdomain:[a-z]+}.gitlab-pages.theorangeone.net`)
      service: service-gitlab-pages
  services:
    service-gitlab:
      loadBalancer:
        servers:
          - url: https://{{ pve_hosts.gitlab.ip }}
    service-gitlab-pages:
      loadBalancer:
        servers:
          - url: http://{{ pve_hosts.gitlab.ip }}:8008
