http:
  middlewares:
    compress:
      compress: {}

    secure-headers:
      headers:
        stsSeconds: 2592000
        contentTypeNosniff: true
        browserXssFilter: true
        customResponseHeaders:
          Server: ''

    # https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network
    floc-block:
      headers:
        customResponseHeaders:
          Permissions-Policy: interest-cohort=()

    tailscale-only:
      ipAllowList:
        sourceRange:
          - "{{ tailscale_cidr }}"
          - "{{ tailscale_cidr_ipv6 }}"
          - "{{ pve_hosts.forrest.ip }}"
          - "{{ pve_hosts.forrest.ipv6 }}"

    private-access:
      ipAllowList:
        sourceRange:
          - "{{ tailscale_cidr }}"
          - "{{ tailscale_cidr_ipv6 }}"
          - "{{ pve_hosts.internal_cidr }}"
          - "{{ pve_hosts.internal_cidr_ipv6 }}"
