http:
  routers:
    router-gitlab:
      rule: Host(`git.theorangeone.net`)
      service: service-gitlab
    router-gitlab-registry:
      rule: Host(`registry.git.theorangeone.net`)
      service: service-gitlab
  services:
    service-gitlab:
      loadBalancer:
        servers:
          - url: https://{{ pve_hosts.gitlab.ip }}
