http:
  routers:
    router-gitlab:
      rule: Host(`git.theorangeone.net`)
      service: service-gitlab
      tls:
        certResolver: le
  services:
    service-gitlab:
      loadBalancer:
        servers:
          - url: https://{{ pve_hosts.gitlab.ip }}
