http:
  routers:
    router-homeassistant:
      rule: Host(`homeassistant.jakehoward.tech`)
      service: service-homeassistant
      middlewares:
        - tailscale-only@file
  services:
    service-homeassistant:
      loadBalancer:
        servers:
          - url: http://{{ pve_hosts.homeassistant.ip }}:8123
