http:
  routers:
    router-jellyfin:
      rule: Host(`media.jakehoward.tech`)
      service: service-jellyfin
  services:
    service-jellyfin:
      loadBalancer:
        servers:
          - url: http://{{ pve_hosts.jellyfin.ip }}:8096
