http:
  routers:
    router-jellyfin:
      rule: Host(`media.jakehoward.tech`)
      service: service-jellyfin
      tls:
        certResolver: le
  services:
    service-jellyfin:
      loadBalancer:
        servers:
          - url: http://{{ pve_hosts.jellyfin.internal_ip }}:8096
