- name: Install restic
  package:
    name: restic

- name: Install runitor on arch
  kewlfft.aur.aur:
    name: runitor-bin
  when: ansible_os_family == 'Archlinux'

- name: Get latest runitor release
  uri:
    url: https://api.github.com/repos/bdd/runitor/releases/latest
    return_content: true
  register: runitor_release
  when: ansible_os_family != 'Archlinux'

- name: Install runitor
  get_url:
    url: https://github.com/bdd/runitor/releases/download/{{ runitor_release.json.tag_name }}/runitor-{{ runitor_release.json.tag_name }}-linux-amd64
    dest: /usr/bin/runitor
    mode: "0755"
  when: ansible_os_family != 'Archlinux'

- name: Make user
  user:
    name: restic
    shell: /bin/nologin
    system: false

- name: Install scripts
  template:
    src: files/{{ item }}
    dest: /home/restic/{{ item }}
    mode: "0700"
    owner: restic
  loop:
    - backrest.sh
    - restic-backup.sh

- name: Install includes files
  copy:
    content: "{{ restic_backup_locations | join('\n') }}"
    dest: /home/restic/restic-include.txt
    mode: "0644"
    owner: restic

- name: Install excludes files
  copy:
    content: "{{ restic_backup_excludes | join('\n') }}"
    dest: /home/restic/restic-excludes.txt
    mode: "0644"
    owner: restic

- name: Set restic binary permissions
  file:
    path: /usr/bin/restic
    mode: "0750"
    owner: root
    group: restic

- name: Install Systemd service
  template:
    src: files/{{ item }}
    dest: /etc/systemd/system/{{ item }}
    mode: "0600"
  loop:
    - restic.service
    - restic.timer
  notify:
    - reload systemd

- name: Enable backups
  systemd_service:
    name: restic.timer
    enabled: true
    state: started

- name: Install HomeAssistant mounts
  include_tasks: homeassistant.yml
  when: ansible_hostname == 'pve-restic'
