- name: Create install directory
  file:
    path: /opt/forgejo-runner
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install config file
  template:
    src: files/config.yml
    dest: /opt/forgejo-runner/config.yml
    mode: "600"
    owner: "{{ docker_user.name }}"
  notify: restart forgejo-runner
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/forgejo-runner/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart forgejo-runner
  become: true
