- name: Install adguardhome
  kewlfft.aur.aur:
    name: adguardhome-bin

- name: Disable resolved stub
  template:
    src: files/resolved-adguardhome.conf
    dest: /etc/systemd/resolved.conf.d/adguardhome.conf
    owner: root
    mode: "0644"
  notify: restart systemd-resolved

- name: Use resolved resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  notify: restart systemd-resolved

- name: Install coredns
  kewlfft.aur.aur:
    name: coredns

- name: Install coredns config file
  template:
    src: files/Corefile
    dest: /etc/coredns/Corefile
    owner: coredns
    mode: "0644"
  notify: restart coredns
