# Cap ARC size to 50% RAM
zfs_arc_size: "{{ (ansible_memtotal_mb * 1024 * 1024) * 0.5 }}"

sanoid_datasets:
  tank:
    use_template: production
    recursive: true
    process_children_only: true

  tank/downloads:
    use_template: replaceable
    recursive: true

sanoid_templates:
  production:
    frequently: 0
    hourly: 36
    daily: 21
    monthly: 3
    yearly: 0
    autosnap: true
    autoprune: true

  replaceable:
    frequently: 0
    hourly: 12
    daily: 5
    monthly: 0
    yearly: 0
    autosnap: true
    autoprune: true
