- name: Create deluge directory
  file:
    path: /opt/deluge
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install deluge compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/deluge/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  notify: restart deluge
  become: true
