- name: Include vault
  include_vars: vault.yml

- name: Create install directory
  file:
    path: /opt/commento
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/commento/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart commento
  become: true

- name: Install nginx config
  template:
    src: files/nginx-docker.conf
    dest: /etc/nginx/http.d/commento.conf
    mode: "0644"
  notify: reload nginx
  become: true
  vars:
    server_name: commento.theorangeone.net
    upstream: commento-commento-1.docker:8080
    ssl_cert_path: /etc/letsencrypt/live/commento.theorangeone.net
